// Country mapping dictionary for ISO-2 codes to fetch high-quality flags from FlagCDN
export const countryMap: Record<string, string> = {
  'afghanistan': 'af',
  'aland islands': 'ax',
  'albania': 'al',
  'algeria': 'dz',
  'american samoa': 'as',
  'andorra': 'ad',
  'angola': 'ao',
  'anguilla': 'ai',
  'antarctica': 'aq',
  'antigua and barbuda': 'ag',
  'argentina': 'ar',
  'armenia': 'am',
  'aruba': 'aw',
  'australia': 'au',
  'austria': 'at',
  'azerbaijan': 'az',
  'bahamas': 'bs',
  'bahrain': 'bh',
  'bangladesh': 'bd',
  'barbados': 'bb',
  'belarus': 'by',
  'belgium': 'be',
  'belize': 'bz',
  'benin': 'bj',
  'bermuda': 'bm',
  'bhutan': 'bt',
  'bolivia': 'bo',
  'bosnia and herzegovina': 'ba',
  'botswana': 'bw',
  'brazil': 'br',
  'brunei': 'bn',
  'bulgaria': 'bg',
  'burkina faso': 'bf',
  'burundi': 'bi',
  'cambodia': 'kh',
  'cameroon': 'cm',
  'canada': 'ca',
  'cape verde': 'cv',
  'cayman islands': 'ky',
  'central african republic': 'cf',
  'chad': 'td',
  'chile': 'cl',
  'china': 'cn',
  'colombia': 'co',
  'comoros': 'km',
  'congo': 'cg',
  'cook islands': 'ck',
  'costa rica': 'cr',
  'cote d\'ivoire': 'ci',
  'croatia': 'hr',
  'cuba': 'cu',
  'cyprus': 'cy',
  'czech republic': 'cz',
  'denmark': 'dk',
  'djibouti': 'dj',
  'dominica': 'dm',
  'dominican republic': 'do',
  'ecuador': 'ec',
  'egypt': 'eg',
  'el salvador': 'sv',
  'equatorial guinea': 'gq',
  'eritrea': 'er',
  'estonia': 'ee',
  'ethiopia': 'et',
  'fiji': 'fj',
  'finland': 'fi',
  'france': 'fr',
  'french guiana': 'gf',
  'gabon': 'ga',
  'gambia': 'gm',
  'georgia': 'ge',
  'germany': 'de',
  'ghana': 'gh',
  'gibraltar': 'gi',
  'greece': 'gr',
  'greenland': 'gl',
  'grenada': 'gd',
  'guadeloupe': 'gp',
  'guam': 'gu',
  'guatemala': 'gt',
  'guernsey': 'gg',
  'guinea': 'gn',
  'guinea-bissau': 'gw',
  'guyana': 'gy',
  'haiti': 'ht',
  'holy see': 'va',
  'honduras': 'hn',
  'hong kong': 'hk',
  'hungary': 'hu',
  'iceland': 'is',
  'india': 'in',
  'indonesia': 'id',
  'iran': 'ir',
  'iraq': 'iq',
  'ireland': 'ie',
  'isle of man': 'im',
  'israel': 'il',
  'italy': 'it',
  'jamaica': 'jm',
  'japan': 'jp',
  'jersey': 'je',
  'jordan': 'jo',
  'kazakhstan': 'kz',
  'kenya': 'ke',
  'kiribati': 'ki',
  'north korea': 'kp',
  'south korea': 'kr',
  'kuwait': 'kw',
  'kyrgyzstan': 'kg',
  'laos': 'la',
  'latvia': 'lv',
  'lebanon': 'lb',
  'lesotho': 'ls',
  'liberia': 'lr',
  'libya': 'ly',
  'liechtenstein': 'li',
  'lithuania': 'lt',
  'luxembourg': 'lu',
  'macao': 'mo',
  'macedonia': 'mk',
  'madagascar': 'mg',
  'malawi': 'mw',
  'malaysia': 'my',
  'maldives': 'mv',
  'mali': 'ml',
  'malta': 'mt',
  'marshall islands': 'mh',
  'martinique': 'mq',
  'mauritania': 'mr',
  'mauritius': 'mu',
  'mayotte': 'yt',
  'mexico': 'mx',
  'micronesia': 'fm',
  'moldova': 'md',
  'monaco': 'mc',
  'mongolia': 'mn',
  'montenegro': 'me',
  'montserrat': 'ms',
  'morocco': 'ma',
  'mozambique': 'mz',
  'myanmar': 'mm',
  'namibia': 'na',
  'nepal': 'np',
  'netherlands': 'nl',
  'new caledonia': 'nc',
  'new zealand': 'nz',
  'nicaragua': 'ni',
  'niger': 'ne',
  'nigeria': 'ng',
  'norway': 'no',
  'oman': 'om',
  'pakistan': 'pk',
  'palau': 'pw',
  'palestine': 'ps',
  'panama': 'pa',
  'papua new guinea': 'pg',
  'paraguay': 'py',
  'peru': 'pe',
  'philippines': 'ph',
  'poland': 'pl',
  'portugal': 'pt',
  'puerto rico': 'pr',
  'qatar': 'qa',
  'reunion': 're',
  'romania': 'ro',
  'russian federation': 'ru',
  'rwanda': 'rw',
  'saint helena': 'sh',
  'saint kitts and nevis': 'kn',
  'saint lucia': 'lc',
  'saint pierre': 'pm',
  'samoa': 'ws',
  'san marino': 'sm',
  'sao tome': 'st',
  'saudi arabia': 'sa',
  'saudi': 'sa',
  'senegal': 'sn',
  'serbia': 'rs',
  'seychelles': 'sc',
  'sierra leone': 'sl',
  'singapore': 'sg',
  'slovakia': 'sk',
  'slovenia': 'si',
  'solomon islands': 'sb',
  'somalia': 'so',
  'south africa': 'za',
  'spain': 'es',
  'sri lanka': 'lk',
  'sudan': 'sd',
  'suriname': 'sr',
  'swaziland': 'sz',
  'sweden': 'se',
  'switzerland': 'ch',
  'syrian arab republic': 'sy',
  'taiwan': 'tw',
  'tajikistan': 'tj',
  'tanzania': 'tz',
  'thailand': 'th',
  'timor-leste': 'tl',
  'togo': 'tg',
  'tonga': 'to',
  'trinidad and tobago': 'tt',
  'tunisia': 'tn',
  'turkey': 'tr',
  'turkmenistan': 'tm',
  'uganda': 'ug',
  'ukraine': 'ua',
  'united arab emirates': 'ae',
  'dubai': 'ae',
  'uae': 'ae',
  'emirates': 'ae',
  'united kingdom': 'gb',
  'uk': 'gb',
  'united states': 'us',
  'usa': 'us',
  'uruguay': 'uy',
  'uzbekistan': 'uz',
  'vanuatu': 'vu',
  'venezuela': 've',
  'vietnam': 'vn',
  'yemen': 'ye',
  'zambia': 'zm',
  'zimbabwe': 'zw'
};

/**
 * Gets the 2-letter country code for a given country name (case-insensitive substring match).
 */
export const getCountryCode = (name: string): string => {
  const norm = (name || '').trim().toLowerCase();
  if (!norm) return '';
  
  // Exact lookup first
  if (countryMap[norm]) return countryMap[norm];

  // Partial matches (e.g. "Saudi" -> "sa", "UK" -> "gb", "USA" -> "us")
  if (norm === 'uk') return 'gb';
  if (norm === 'usa') return 'us';

  // Substring match
  for (const [key, value] of Object.entries(countryMap)) {
    if (norm.includes(key) || key.includes(norm)) {
      return value;
    }
  }
  return '';
};

/**
 * Returns a FlagCDN image URL for the country name, or a default fallback if not found.
 */
export const getCountryFlagUrl = (countryName: string): string => {
  const code = getCountryCode(countryName);
  if (code) {
    return `https://flagcdn.com/w80/${code}.png`;
  }
  return '';
};

/**
 * Ensures a candidate name is beautifully formatted with spaces between CamelCase, snake_case or squished patterns.
 */
export const formatCandidateName = (name: string): string => {
  if (!name) return '';
  // Convert camelCase like "ImNameren" -> "Im Nameren"
  let formatted = name.replace(/([a-z])([A-Z])/g, '$1 $2');
  // Convert snake_case or dashes like "IM_NAMEREN" or "IM-NAMEREN" -> "IM NAMEREN"
  formatted = formatted.replace(/[_-]+/g, ' ');
  // Strip excessive spaces
  formatted = formatted.replace(/\s+/g, ' ');
  return formatted.trim();
};

